"""Add calendar sync token and watch channel fields

Revision ID: 099a41300f06
Revises: 332cbeb577f1
Create Date: 2026-09-02 18:11:10.845325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '099a41300f06'
down_revision = '332cbeb577f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sync_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('watch_channel_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('watch_resource_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('watch_channel_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('watch_expiration', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_calendar_accounts_watch_channel_id'), ['watch_channel_id'], unique=True)

    with op.batch_alter_table('sync_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trigger', sa.String(length=20), nullable=False, server_default='manual'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_logs', schema=None) as batch_op:
        batch_op.drop_column('trigger')

    with op.batch_alter_table('calendar_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_accounts_watch_channel_id'))
        batch_op.drop_column('watch_expiration')
        batch_op.drop_column('watch_channel_token')
        batch_op.drop_column('watch_resource_id')
        batch_op.drop_column('watch_channel_id')
        batch_op.drop_column('sync_token')

    # ### end Alembic commands ###
